import { Product, Category, Supplier } from './lib/types';

// Función que genera los productos adicionales
const createAdditionalProducts = (categories: Category[], suppliers: Supplier[]): Product[] => [
  {
    id: '10',
    name: 'Café de Especialidad Brasil Santos 1kg',
    description: 'Café de tueste medio-oscuro con notas de chocolate y nueces. Ideal para espresso y bebidas con leche.',
    sku: 'CAF-BRA-010',
    price: 420,
    salePrice: 380,
    images: [
      'https://images.pexels.com/photos/414555/pexels-photo-414555.jpeg',
      'https://images.pexels.com/photos/977878/pexels-photo-977878.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 65,
    minOrderQuantity: 3,
    specifications: {
      'Origen': 'Brasil',
      'Tueste': 'Medio-Oscuro',
      'Notas': 'Chocolate, Nueces, Caramelo',
      'Método recomendado': 'Espresso, Prensa Francesa',
      'Intensidad': '7/10',
      'Peso': '1kg',
    },
    isActive: true,
    createdAt: '2024-01-15T09:20:00Z',
    updatedAt: '2024-03-05T15:30:00Z',
  },
  {
    id: '11',
    name: 'Café Colombia Supremo 500g',
    description: 'Grano de alta calidad de las montañas colombianas, con un perfil equilibrado y notas cítricas.',
    sku: 'CAF-COL-011',
    price: 290,
    images: [
      'https://images.pexels.com/photos/1170659/pexels-photo-1170659.jpeg',
      'https://images.pexels.com/photos/685527/pexels-photo-685527.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 120,
    minOrderQuantity: 2,
    specifications: {
      'Origen': 'Colombia',
      'Tueste': 'Medio',
      'Notas': 'Cítricos, Caramelo, Vainilla',
      'Método recomendado': 'Pour Over, Aeropress',
      'Intensidad': '6/10',
      'Peso': '500g',
    },
    isActive: true,
    createdAt: '2024-01-20T10:15:00Z',
    updatedAt: '2024-03-10T11:25:00Z',
  },
  {
    id: '12',
    name: 'Máquina Semi-Automática Barista Pro',
    description: 'Máquina de espresso semi-automática con molino integrado y pantalla LCD. Control preciso de temperatura y presión.',
    sku: 'MAQ-ESP-012',
    price: 18500,
    salePrice: 16900,
    images: [
      'https://images.pexels.com/photos/2608941/pexels-photo-2608941.jpeg',
      'https://images.pexels.com/photos/6400992/pexels-photo-6400992.jpeg',
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 8,
    minOrderQuantity: 1,
    specifications: {
      'Potencia': '1680W',
      'Capacidad tanque': '2L',
      'Presión': '15 bar',
      'Dimensiones': '40 x 33 x 41 cm',
      'Peso': '13.5kg',
      'Voltaje': '220V',
    },
    isActive: true,
    createdAt: '2024-01-25T08:30:00Z',
    updatedAt: '2024-03-15T14:45:00Z',
  },
  {
    id: '13',
    name: 'Báscula Digital de Precisión',
    description: 'Báscula digital de alta precisión con temporizador integrado. Ideal para medir dosis exactas de café.',
    sku: 'ACC-BAS-013',
    price: 850,
    salePrice: 750,
    images: [
      'https://images.pexels.com/photos/4226896/pexels-photo-4226896.jpeg',
      'https://images.pexels.com/photos/1482803/pexels-photo-1482803.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 30,
    minOrderQuantity: 2,
    specifications: {
      'Capacidad máxima': '2kg',
      'Precisión': '0.1g',
      'Temporizador': 'Sí',
      'Alimentación': 'Batería recargable',
      'Dimensiones': '15 x 13 x 2 cm',
    },
    isActive: true,
    createdAt: '2024-02-05T11:20:00Z',
    updatedAt: '2024-03-18T09:15:00Z',
  },
  {
    id: '14',
    name: 'Molinillo de Café Profesional',
    description: 'Molinillo de café con 40 ajustes de molienda y tolva de 250g. Motor silencioso y muelas de acero.',
    sku: 'ACC-MOL-014',
    price: 3950,
    images: [
      'https://images.pexels.com/photos/3933498/pexels-photo-3933498.jpeg',
      'https://images.pexels.com/photos/1459339/pexels-photo-1459339.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 15,
    minOrderQuantity: 1,
    specifications: {
      'Potencia': '150W',
      'Capacidad tolva': '250g',
      'Ajustes de molienda': '40',
      'Material muelas': 'Acero inoxidable',
      'Dimensiones': '35 x 12 x 23 cm',
    },
    isActive: true,
    createdAt: '2024-02-10T14:30:00Z',
    updatedAt: '2024-03-20T16:40:00Z',
  },
  {
    id: '15',
    name: 'Café Etiopía Yirgacheffe 500g',
    description: 'Café de origen único con notas florales y afrutadas características de la región de Yirgacheffe.',
    sku: 'CAF-ETI-015',
    price: 360,
    salePrice: 320,
    images: [
      'https://images.pexels.com/photos/2067628/pexels-photo-2067628.jpeg',
      'https://images.pexels.com/photos/2074122/pexels-photo-2074122.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 50,
    minOrderQuantity: 2,
    specifications: {
      'Origen': 'Etiopía',
      'Tueste': 'Medio-Ligero',
      'Notas': 'Flores, Bergamota, Miel',
      'Método recomendado': 'Pour Over, Chemex',
      'Intensidad': '5/10',
      'Peso': '500g',
    },
    isActive: true,
    createdAt: '2024-02-15T10:45:00Z',
    updatedAt: '2024-03-22T13:20:00Z',
  },
  {
    id: '16',
    name: 'Jarra de Leche Profesional 600ml',
    description: 'Jarra de acero inoxidable con diseño ergonómico para un vertido preciso. Ideal para crear arte latte.',
    sku: 'ACC-JAR-016',
    price: 450,
    images: [
      'https://images.pexels.com/photos/7474390/pexels-photo-7474390.jpeg',
      'https://images.pexels.com/photos/9012110/pexels-photo-9012110.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 40,
    minOrderQuantity: 3,
    specifications: {
      'Material': 'Acero inoxidable 304',
      'Capacidad': '600ml',
      'Mango': 'Ergonómico aislante',
      'Pico': 'Vertido fino',
      'Dimensiones': '15 x 9 x 12 cm',
    },
    isActive: true,
    createdAt: '2024-02-20T09:10:00Z',
    updatedAt: '2024-03-25T11:30:00Z',
  },
  {
    id: '17',
    name: 'Máquina de Filtro Comercial',
    description: 'Máquina de café de filtro de alto rendimiento con capacidad para 100 tazas por hora. Ideal para cafeterías con alto volumen.',
    sku: 'MAQ-FIL-017',
    price: 12500,
    salePrice: 11000,
    images: [
      'https://images.pexels.com/photos/2467287/pexels-photo-2467287.jpeg',
      'https://images.pexels.com/photos/3095224/pexels-photo-3095224.jpeg',
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 5,
    minOrderQuantity: 1,
    specifications: {
      'Capacidad': '100 tazas/hora',
      'Potencia': '2200W',
      'Tanque de agua': '4L',
      'Dimensiones': '35 x 40 x 55 cm',
      'Peso': '18kg',
      'Voltaje': '220V',
    },
    isActive: true,
    createdAt: '2024-02-25T13:50:00Z',
    updatedAt: '2024-03-27T15:15:00Z',
  },
  {
    id: '18',
    name: 'Café Kenia AA 1kg',
    description: 'Café de origen único de la región de Nyeri con notas brillantes de frutos rojos y un cuerpo aterciopelado.',
    sku: 'CAF-KEN-018',
    price: 490,
    images: [
      'https://images.pexels.com/photos/942680/pexels-photo-942680.jpeg',
      'https://images.pexels.com/photos/2396220/pexels-photo-2396220.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 35,
    minOrderQuantity: 2,
    specifications: {
      'Origen': 'Kenia',
      'Tueste': 'Medio',
      'Notas': 'Frutos rojos, Grosellas, Chocolate negro',
      'Método recomendado': 'Pour Over, Aeropress',
      'Intensidad': '7/10',
      'Peso': '1kg',
    },
    isActive: true,
    createdAt: '2024-03-01T08:40:00Z',
    updatedAt: '2024-03-29T10:10:00Z',
  },
  {
    id: '19',
    name: 'Set de Filtros Reutilizables',
    description: 'Set de 4 filtros reutilizables de acero inoxidable compatible con múltiples métodos de preparación.',
    sku: 'ACC-FIL-019',
    price: 580,
    salePrice: 520,
    images: [
      'https://images.pexels.com/photos/9084535/pexels-photo-9084535.jpeg',
      'https://images.pexels.com/photos/7474347/pexels-photo-7474347.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 55,
    minOrderQuantity: 2,
    specifications: {
      'Material': 'Acero inoxidable',
      'Cantidad': '4 filtros',
      'Compatibilidad': 'V60, Chemex, Aeropress, Kalita',
      'Lavado': 'Apto para lavavajillas',
      'Dimensiones': 'Varios tamaños',
    },
    isActive: true,
    createdAt: '2024-03-05T15:25:00Z',
    updatedAt: '2024-03-30T12:35:00Z',
  },
  {
    id: '20',
    name: 'Café Guatemala Antigua 500g',
    description: 'Café de las tierras altas de Guatemala con un perfil equilibrado y notas de chocolate y especias.',
    sku: 'CAF-GUA-020',
    price: 310,
    salePrice: 280,
    images: [
      'https://images.pexels.com/photos/2878730/pexels-photo-2878730.jpeg',
      'https://images.pexels.com/photos/1879321/pexels-photo-1879321.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 70,
    minOrderQuantity: 3,
    specifications: {
      'Origen': 'Guatemala',
      'Tueste': 'Medio',
      'Notas': 'Chocolate, Canela, Naranja',
      'Método recomendado': 'Espresso, Moka',
      'Intensidad': '6/10',
      'Peso': '500g',
    },
    isActive: true,
    createdAt: '2024-03-10T11:15:00Z',
    updatedAt: '2024-04-01T14:20:00Z',
  },
  {
    id: '21',
    name: 'Prensa Francesa de Cristal 1L',
    description: 'Prensa francesa de cristal borosilicato resistente al calor con filtro de acero inoxidable.',
    sku: 'ACC-PRE-021',
    price: 690,
    images: [
      'https://images.pexels.com/photos/6541390/pexels-photo-6541390.jpeg',
      'https://images.pexels.com/photos/6542384/pexels-photo-6542384.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 25,
    minOrderQuantity: 2,
    specifications: {
      'Material': 'Cristal borosilicato y acero inoxidable',
      'Capacidad': '1L (8 tazas)',
      'Filtro': 'Acero inoxidable de doble malla',
      'Resistencia': 'Apto para lavavajillas',
      'Dimensiones': '15 x 15 x 22 cm',
    },
    isActive: true,
    createdAt: '2024-03-15T09:30:00Z',
    updatedAt: '2024-04-03T13:40:00Z',
  },
  {
    id: '22',
    name: 'Kit Básico de Barista',
    description: 'Kit completo para baristas principiantes: tamper, jarra de leche, termómetro y cepillos de limpieza.',
    sku: 'ACC-KIT-022',
    price: 1850,
    salePrice: 1650,
    images: [
      'https://images.pexels.com/photos/3020919/pexels-photo-3020919.jpeg',
      'https://images.pexels.com/photos/4226896/pexels-photo-4226896.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 18,
    minOrderQuantity: 1,
    specifications: {
      'Contenido': 'Tamper 58mm, Jarra 350ml, Termómetro digital, Set de cepillos',
      'Material': 'Acero inoxidable',
      'Caja': 'Estuche de almacenamiento',
      'Guía': 'Manual básico de barista',
    },
    isActive: true,
    createdAt: '2024-03-20T13:45:00Z',
    updatedAt: '2024-04-05T10:15:00Z',
  },
  {
    id: '23',
    name: 'Máquina de Cápsulas Profesional',
    description: 'Máquina para cápsulas de alta velocidad con sistema de calentamiento rápido. Ideal para oficinas.',
    sku: 'MAQ-CAP-023',
    price: 8500,
    images: [
      'https://images.pexels.com/photos/4350059/pexels-photo-4350059.jpeg',
      'https://images.pexels.com/photos/4350075/pexels-photo-4350075.jpeg',
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 12,
    minOrderQuantity: 1,
    specifications: {
      'Potencia': '1500W',
      'Capacidad depósito': '2.5L',
      'Presión': '19 bar',
      'Tiempo calentamiento': '25 segundos',
      'Dimensiones': '28 x 38 x 22 cm',
      'Peso': '7kg',
    },
    isActive: true,
    createdAt: '2024-03-25T16:20:00Z',
    updatedAt: '2024-04-08T11:50:00Z',
  },
  {
    id: '24',
    name: 'Café Costa Rica Tarrazu 1kg',
    description: 'Café de altura con notas de frutas tropicales y un cuerpo medio-completo. Cultivo sostenible.',
    sku: 'CAF-COS-024',
    price: 460,
    salePrice: 410,
    images: [
      'https://images.pexels.com/photos/1627933/pexels-photo-1627933.jpeg',
      'https://images.pexels.com/photos/2260867/pexels-photo-2260867.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 40,
    minOrderQuantity: 2,
    specifications: {
      'Origen': 'Costa Rica',
      'Tueste': 'Medio',
      'Notas': 'Mango, Piña, Miel',
      'Método recomendado': 'Pour Over, Prensa Francesa',
      'Intensidad': '6/10',
      'Peso': '1kg',
    },
    isActive: true,
    createdAt: '2024-03-28T08:50:00Z',
    updatedAt: '2024-04-10T15:30:00Z',
  },
];

// Exportar la función que crea los productos adicionales
export default createAdditionalProducts;
