import { Product, Category, Supplier } from "./lib/types";

// Function that generates additional products
const createAdditionalProducts = (
  categories: Category[],
  suppliers: Supplier[]
): Product[] => [  {
    id: "10",
    name: "BIOCAF CLEANING KIT COMBO",
    description:
      "Café brasileño de la región Santos con tueste medio-oscuro, notas de chocolate y nueces. Ideal para espresso y bebidas con leche.",
    sku: "COF-BRA-010",
    price: 420,
    salePrice: 380,
    images: [
      "https://m.media-amazon.com/images/I/61Ql4TcMlrL.jpg",
      "https://caffecorsini.com/cdn/shop/products/BrasilSantos_500g.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 65,
    minOrderQuantity: 3,
    specifications: {
      Origin: "Santos, São Paulo, Brazil",
      Roast: "Medium-Dark",
      Notes: "Chocolate, Nueces, Caramelo",
      "Recommended Method": "Espresso, French Press",
      Intensity: "7/10",
      Weight: "1kg",
      Processing: "Natural",
      Altitude: "750-1050m",
    },
    isActive: true,
    createdAt: "2024-01-15T09:20:00Z",
    updatedAt: "2024-03-05T15:30:00Z",
  },  {
    id: "11",
    name: "Res tierra Colombia CASE 6 S.P.RES TIERRA COL FLT 226,8 G",
    description:
      "Granos de alta calidad de las montañas colombianas, con perfil equilibrado y notas cítricas características del grado Supremo.",
    sku: "COF-COL-011",
    price: 290,
    images: [
      "https://www.supercafes.es/gestlab/products/1353/big_big_71llCma5qCL._AC_SL1500_.jpg",
      "https://www.roastmasters.com/images/thumbnails/250/250/detailed/0/colombia-supremo-green-coffee-beans.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 120,
    minOrderQuantity: 2,
    specifications: {
      Origin: "Medellín, Antioquia, Colombia",
      Roast: "Medium",
      Notes: "Citrus, Caramelo, Vainilla",
      "Recommended Method": "Pour Over, Aeropress",
      Intensity: "6/10",
      Weight: "500g",
      Grade: "Supremo (Screen 17+)",
      Processing: "Washed",
    },
    isActive: true,
    createdAt: "2024-01-20T10:15:00Z",
    updatedAt: "2024-03-10T11:25:00Z",
  },  {
    id: "120",
    name: "Gran Riserva CASE 6 BAGS GR RISERVA FILT DARK R 1000B",
    description:
      "Máquina de espresso semiautomática con molinillo integrado y pantalla LCD. Control preciso de temperatura y presión para uso profesional.",
    sku: "MAC-ESP-012",
    price: 18500,
    salePrice: 16900,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNy-gY5pO4mU5wSAQkGV4eg63r4VUI72C2GQ&s",
      "https://www.maxima.com/images/products/large/espresso-machine-2-group-automatic.jpg",
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 8,
    minOrderQuantity: 1,
    specifications: {
      Power: "1680W",
      "Tank Capacity": "2L",
      Pressure: "15 bar",
      Groups: "2",
      Dimensions: "40 x 33 x 41 cm",
      Weight: "13.5kg",
      Voltage: "220V",
      Features: "Built-in grinder, LCD display",
    },
    isActive: true,
    createdAt: "2024-01-25T08:30:00Z",
    updatedAt: "2024-03-15T14:45:00Z",
  },
  {
    id: "13",
    name: "Urnex Clearly Cold – Cold Brew Cleaner",
    description:
      "Báscula digital de alta precisión con temporizador integrado. Ideal para medir dosis exactas de café con precisión de 0.1g.",
    sku: "ACC-SCA-013",
    price: 850,
    salePrice: 750,
    images: [
      "https://static.wixstatic.com/media/fd441e_18ccee5d36f341b492da29770164ad68~mv2.jpg/v1/fill/w_480,h_480,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/fd441e_18ccee5d36f341b492da29770164ad68~mv2.jpg",
      "https://baristasupplies.com.au/cdn/shop/products/digital-scale-with-timer-barista-supplies.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 30,
    minOrderQuantity: 2,
    specifications: {
      "Maximum Capacity": "3kg",
      Precision: "0.1g",
      Timer: "Built-in",
      "Power Supply": "Rechargeable battery",
      Dimensions: "19.4 x 13 x 3.1 cm",
      Material: "Stainless steel housing",
      Features: "Waterproof, Non-slip pad",
    },
    isActive: true,
    createdAt: "2024-02-05T11:20:00Z",
    updatedAt: "2024-03-18T09:15:00Z",
  },
  {
    id: "14",
    name: "BIOCAF MILK FROTHER CLEANING LIQUID, 1 L",
    description:
      "Molinillo de café con fresas de acero y 40 configuraciones de molienda. Motor silencioso con tolva de 250g para uso profesional.",
    sku: "ACC-GRI-014",
    price: 3950,
    images: [
      "https://i5.walmartimages.com/seo/Starbucks-Espresso-Roast-Dark-Roast-Ground-Coffee-12-Ounce-Bag_b1979375-0814-4624-8f83-78d3efbddbbe.11ab07245717b8aac6139d8395628900.jpeg",
      "https://www.williams-sonoma.com/wsimgs/rk/images/dp/wcm/202341/0018/braun-burr-coffee-grinder-c.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 15,
    minOrderQuantity: 1,
    specifications: {
      Power: "150W",
      "Hopper Capacity": "250g",
      "Grind Settings": "40",
      "Burr Material": "Stainless steel",
      Dimensions: "35 x 12 x 23 cm",
      Features: "Overheat protection, Auto-shutoff",
      "Grind Types": "Super-fine to coarse",
    },
    isActive: true,
    createdAt: "2024-02-10T14:30:00Z",
    updatedAt: "2024-03-20T16:40:00Z",
  },  {
    id: "15",
    name: "SPECIALTY ETHIOPIAN COFFEE",
    description:
      "Café de origen único con notas florales y afrutadas características de la región Yirgacheffe. Procesado lavado y secado al sol.",
    sku: "COF-ETH-015",
    price: 360,
    salePrice: 320,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRW7vc8GXb6VHO8Rm8_tWWwau5EXoeJhYwrxQ&s",
      "https://konjocoffee.co.uk/wp-content/uploads/2023/03/yirgacheffe-ethiopian-coffee-beans.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 50,
    minOrderQuantity: 2,
    specifications: {
      Origin: "Yirgacheffe, Ethiopia",
      Roast: "Medium-Light",
      Notes: "Floral, Bergamot, Honey, Jasmine",
      "Recommended Method": "Pour Over, Chemex",
      Intensity: "5/10",
      Weight: "500g",
      Altitude: "1700-2200m",
      Processing: "Washed, Sun-dried",
    },
    isActive: true,
    createdAt: "2024-02-15T10:45:00Z",
    updatedAt: "2024-03-22T13:20:00Z",
  },  {
    id: "16",
    name: "MILK PITCHER PROFESSIONAL",
    description:
      "Jarra de acero inoxidable con diseño ergonómico para vertido preciso. Ideal para crear arte latte con pico especializado.",
    sku: "ACC-PIT-016",
    price: 450,
    images: [
      "https://www.goccedisicilia.com/9278-large_default/bourbon-barley-espresso-18-compostable-pods-ese-44-mm-paper-filter.jpg",
      "https://www.espresso.co.nz/wp-content/uploads/2020/08/milk-steaming-jug-600ml.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 40,
    minOrderQuantity: 3,
    specifications: {
      Material: "304 Stainless steel",
      Capacity: "600ml",
      Handle: "Ergonomic insulated",
      Spout: "Tapered for latte art",
      Dimensions: "15 x 9 x 12 cm",
      Features: "Heat resistant, Dishwasher safe",
    },
    isActive: true,
    createdAt: "2024-02-20T09:10:00Z",
    updatedAt: "2024-03-25T11:30:00Z",
  },  {
    id: "17",
    name: "SPECIALTY COFFEE SAMPLER KIT",
    description:
      "Cafetera de goteo de alto rendimiento con capacidad para 100 tazas por hora. Ideal para cafeterías de alto volumen.",
    sku: "MAC-FIL-017",
    price: 12500,
    salePrice: 11000,
    images: [
      "https://www.deathwishcoffee.com/cdn/shop/files/Light_Roast_16oz_Ground_Angle_DTC_A1_2.jpg?v=1727439735",
      "https://www.katom.com/images/products/bunn-cwtf15-3-0203.jpg",
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 5,
    minOrderQuantity: 1,
    specifications: {
      Capacity: "100 cups/hour",
      Power: "2200W",
      "Water Tank": "4L",
      Dimensions: "35 x 40 x 55 cm",
      Weight: "18kg",
      Voltage: "220V",
      Type: "Commercial pour-over",
      Features: "Pulse brew, Pre-infusion",
    },
    isActive: true,
    createdAt: "2024-02-25T13:50:00Z",
    updatedAt: "2024-03-27T15:15:00Z",
  },
  {
    id: "18",
    name: "SOFT PACKS ITALIAN ROAST 340 GROUND",
    description:
      "Café de origen único de la región Nyeri con notas brillantes de frutos rojos y cuerpo aterciopelado. Grado AA premium.",
    sku: "COF-KEN-018",
    price: 490,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX2-xRH-8caEVYf8C1693pg6UsBNtvoeKxsQ&s",
      "https://volcanicacoffee.com/cdn/shop/products/kenya-aa-coffee-beans.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 35,
    minOrderQuantity: 2,
    specifications: {
      Origin: "Nyeri, Kenya",
      Roast: "Medium",
      Notes: "Red fruits, Currants, Dark chocolate",
      "Recommended Method": "Pour Over, Aeropress",
      Intensity: "7/10",
      Weight: "1kg",
      Grade: "AA (Screen 17+)",
      Altitude: "6000 feet",
      Processing: "Washed",
    },
    isActive: true,
    createdAt: "2024-03-01T08:40:00Z",
    updatedAt: "2024-03-29T10:10:00Z",
  },  {
    id: "19",
    name: "REUSABLE FILTER SET PREMIUM",
    description:
      "Set de 4 filtros reutilizables de acero inoxidable compatibles con múltiples métodos de preparación. Eco-friendly y duraderos.",
    sku: "ACC-FIL-019",
    price: 580,
    salePrice: 520,
    images: [
      "https://www.wholelattelove.com/cdn/shop/products/4816_original_lavazza-dek-decaf-espresso-whole-bean-coffee.jpg?v=1592510470&width=1200",
      "https://kitchenxperts.com/wp-content/uploads/2023/10/v60-stainless-steel-reusable-filter.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 55,
    minOrderQuantity: 2,
    specifications: {
      Material: "Stainless steel",
      Quantity: "4 filters",
      Compatibility: "V60, Chemex, Aeropress, Kalita",
      Washing: "Dishwasher safe",
      Dimensions: "Various sizes",
      Mesh: "Fine honeycomb design",
      Features: "Eco-friendly, Reusable",
    },
    isActive: true,
    createdAt: "2024-03-05T15:25:00Z",
    updatedAt: "2024-03-30T12:35:00Z",
  },  {
    id: "20",
    name: "PREMIUM COFFEE GIFT SET",
    description:
      "Café de las tierras altas de Guatemala con perfil equilibrado y notas de chocolate y especias. Cultivado en suelo volcánico.",
    sku: "COF-GUA-020",
    price: 310,
    salePrice: 280,
    images: [
      "https://ecscoffee.com/cdn/shop/files/Lavazza-Classy-MINI-Capsule-Espresso-Machine-1.jpg?v=1727195752",
      "https://www.guatemalancoffees.com/images/antigua-coffee-beans-specialty.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 70,
    minOrderQuantity: 3,
    specifications: {
      Origin: "Antigua, Guatemala",
      Roast: "Medium",
      Notes: "Chocolate, Cinnamon, Orange",
      "Recommended Method": "Espresso, Moka",
      Intensity: "6/10",
      Weight: "500g",
      Altitude: "4600-5600 feet",
      Processing: "Washed",
      Grade: "SHB (Strictly Hard Bean)",
    },
    isActive: true,
    createdAt: "2024-03-10T11:15:00Z",
    updatedAt: "2024-04-01T14:20:00Z",
  },  {
    id: "21",
    name: "FILTER COFFEE SET DELUXE",
    description:
      "Prensa francesa de vidrio borosilicato resistente al calor con filtro de acero inoxidable. Capacidad para 8 tazas.",
    sku: "ACC-FRP-021",
    price: 690,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqHpkDKftVbuezqLj4SWwTihRlqLssPpaQ-A&s",
      "https://shop.original-unverpackt.de/cdn/shop/products/french-press-glass-1l.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 25,
    minOrderQuantity: 2,
    specifications: {
      Material: "Borosilicate glass and stainless steel",
      Capacity: "1L (8 cups)",
      Filter: "Double mesh stainless steel",
      Resistance: "Heat-resistant, Dishwasher safe",
      Dimensions: "23.6 x 15 x 10.1 cm",
      Weight: "637g",
      Features: "Microwave safe, Non-porous surface",
    },
    isActive: true,
    createdAt: "2024-03-15T09:30:00Z",
    updatedAt: "2024-04-03T13:40:00Z",
  },  {
    id: "22",
    name: "BARISTA PROFESSIONAL TOOLKIT",
    description:
      "Kit completo para baristas principiantes: tamper, jarra de leche, termómetro y cepillos de limpieza. Todo lo esencial incluido.",
    sku: "ACC-KIT-022",
    price: 1850,
    salePrice: 1650,
    images: [
      "https://dailycoffeenews.com/wp-content/uploads/2017/02/urnex-cold-brew.jpg",
      "https://www.corporatecoffee.com.au/wp-content/uploads/2023/05/basic-barista-startup-kit.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 18,
    minOrderQuantity: 1,
    specifications: {
      Contents:
        "Tamper 58mm, Pitcher 360ml/600ml, Digital thermometer, Brush set, Knock box, Scales",
      Material: "Stainless steel",
      Box: "Storage case included",
      Guide: "Basic barista manual",
      Tamper: "58mm stainless steel",
      Scales: "500g capacity",
    },
    isActive: true,
    createdAt: "2024-03-20T13:45:00Z",
    updatedAt: "2024-04-05T10:15:00Z",
  },  {
    id: "23",
    name: "PREMIUM CAPSULE SYSTEM PRO",
    description:
      "Máquina de cápsulas de alta velocidad con sistema de calentamiento rápido. Compatible con sistema Nespresso para oficinas.",
    sku: "MAC-CAP-023",
    price: 8500,
    images: [
      "https://roshcookwares.in/cdn/shop/files/7_b280de7f-e019-4f16-88b9-1243f4b368c2.jpg?v=1725533480&width=1946",
      "https://www.nespresso.com/shared_res/agility/n-components/product-media/vertuo-machine-black.jpg",
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 12,
    minOrderQuantity: 1,
    specifications: {
      Power: "1500W",
      "Tank Capacity": "2.5L",
      Pressure: "19 bar",
      "Heating Time": "25 seconds",
      Dimensions: "28 x 38 x 22 cm",
      Weight: "7kg",
      Compatibility: "Nespresso system",
      Features: "Barcode reading, Auto-shutoff",
    },
    isActive: true,
    createdAt: "2024-03-25T16:20:00Z",
    updatedAt: "2024-04-08T11:50:00Z",
  },  {
    id: "24",
    name: "PREMIUM COLD BREW KIT",
    description:
      "Café de alta altitud con notas de frutas tropicales y cuerpo medio-completo. Cultivo sostenible de la región Los Santos.",
    sku: "COF-COS-024",
    price: 460,
    salePrice: 410,
    images: [
      "https://2.wlimg.com/product_images/bc-full/2023/2/3944089/gemini-fresh-filter-coffee-maker-1675406579-6745835.jpeg",
      "https://www.costaricancoffees.com/images/tarrazu-coffee-beans-premium.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 40,
    minOrderQuantity: 2,
    specifications: {
      Origin: "Tarrazú, Costa Rica",
      Roast: "Medium",
      Notes: "Mango, Pineapple, Honey, Chocolate",
      "Recommended Method": "Pour Over, French Press",
      Intensity: "6/10",
      Weight: "1kg",
      Altitude: "1200-1900m",
      Processing: "Washed",
      Grade: "SHB (Strictly Hard Bean)",
    },
    isActive: true,
    createdAt: "2024-03-28T08:50:00Z",
    updatedAt: "2024-04-10T15:30:00Z",
  },
];

// Exportar la función que crea los productos adicionales
export default createAdditionalProducts;
