import { Product, Category, Supplier } from './lib/types';

// Function that generates additional products
const createAdditionalProducts = (categories: Category[], suppliers: Supplier[]): Product[] => [{
    id: '10',
    name: 'Brazil Santos Specialty Coffee 1kg',
    description: 'Medium-dark roast coffee with notes of chocolate and nuts. Ideal for espresso and milk-based drinks.',
    sku: 'COF-BRA-010',
    price: 420,
    salePrice: 380,
    images: [
      'https://images.pexels.com/photos/414555/pexels-photo-414555.jpeg',
      'https://images.pexels.com/photos/977878/pexels-photo-977878.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 65,
    minOrderQuantity: 3,
    specifications: {
      'Origin': 'Brazil',
      'Roast': 'Medium-Dark',
      'Notes': 'Chocolate, Nuts, Caramel',
      'Recommended Method': 'Espresso, French Press',
      'Intensity': '7/10',
      'Weight': '1kg',
    },
    isActive: true,
    createdAt: '2024-01-15T09:20:00Z',
    updatedAt: '2024-03-05T15:30:00Z',
  },  {
    id: '11',
    name: 'Colombia Supremo Coffee 500g',
    description: 'High-quality beans from Colombian mountains, with a balanced profile and citrus notes.',
    sku: 'COF-COL-011',
    price: 290,
    images: [
      'https://images.pexels.com/photos/1170659/pexels-photo-1170659.jpeg',
      'https://images.pexels.com/photos/685527/pexels-photo-685527.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 120,
    minOrderQuantity: 2,
    specifications: {
      'Origin': 'Colombia',
      'Roast': 'Medium',
      'Notes': 'Citrus, Caramel, Vanilla',      'Recommended Method': 'Pour Over, Aeropress',
      'Intensity': '6/10',
      'Weight': '500g',
    },
    isActive: true,
    createdAt: '2024-01-20T10:15:00Z',
    updatedAt: '2024-03-10T11:25:00Z',
  },  {
    id: '12',
    name: 'Barista Pro Semi-Automatic Machine',
    description: 'Semi-automatic espresso machine with built-in grinder and LCD screen. Precise temperature and pressure control.',
    sku: 'MAC-ESP-012',
    price: 18500,
    salePrice: 16900,
    images: [
      'https://images.pexels.com/photos/2608941/pexels-photo-2608941.jpeg',
      'https://images.pexels.com/photos/6400992/pexels-photo-6400992.jpeg',
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 8,
    minOrderQuantity: 1,    specifications: {
      'Power': '1680W',
      'Tank Capacity': '2L',
      'Pressure': '15 bar',
      'Dimensions': '40 x 33 x 41 cm',
      'Weight': '13.5kg',
      'Voltage': '220V',
    },
    isActive: true,
    createdAt: '2024-01-25T08:30:00Z',
    updatedAt: '2024-03-15T14:45:00Z',
  },
  {    id: '13',
    name: 'Precision Digital Scale',
    description: 'High-precision digital scale with built-in timer. Ideal for measuring exact coffee doses.',
    sku: 'ACC-SCA-013',
    price: 850,
    salePrice: 750,
    images: [
      'https://images.pexels.com/photos/4226896/pexels-photo-4226896.jpeg',
      'https://images.pexels.com/photos/1482803/pexels-photo-1482803.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 30,
    minOrderQuantity: 2,    specifications: {
      'Maximum Capacity': '2kg',
      'Precision': '0.1g',
      'Timer': 'Yes',
      'Power Supply': 'Rechargeable battery',
      'Dimensions': '15 x 13 x 2 cm',
    },
    isActive: true,
    createdAt: '2024-02-05T11:20:00Z',
    updatedAt: '2024-03-18T09:15:00Z',
  },  {
    id: '14',
    name: 'Professional Coffee Grinder',
    description: 'Coffee grinder with 40 grind settings and 250g hopper. Quiet motor and steel burrs.',
    sku: 'ACC-GRI-014',
    price: 3950,
    images: [
      'https://images.pexels.com/photos/3933498/pexels-photo-3933498.jpeg',
      'https://images.pexels.com/photos/1459339/pexels-photo-1459339.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 15,
    minOrderQuantity: 1,    specifications: {
      'Power': '150W',
      'Hopper Capacity': '250g',
      'Grind Settings': '40',
      'Burr Material': 'Stainless steel',
      'Dimensions': '35 x 12 x 23 cm',
    },
    isActive: true,
    createdAt: '2024-02-10T14:30:00Z',
    updatedAt: '2024-03-20T16:40:00Z',
  },  {
    id: '15',
    name: 'Ethiopia Yirgacheffe Coffee 500g',
    description: 'Single-origin coffee with floral and fruity notes characteristic of the Yirgacheffe region.',
    sku: 'COF-ETH-015',
    price: 360,
    salePrice: 320,
    images: [
      'https://images.pexels.com/photos/2067628/pexels-photo-2067628.jpeg',
      'https://images.pexels.com/photos/2074122/pexels-photo-2074122.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 50,
    minOrderQuantity: 2,    specifications: {
      'Origin': 'Ethiopia',
      'Roast': 'Medium-Light',
      'Notes': 'Floral, Bergamot, Honey',
      'Recommended Method': 'Pour Over, Chemex',
      'Intensity': '5/10',
      'Weight': '500g',
    },
    isActive: true,
    createdAt: '2024-02-15T10:45:00Z',
    updatedAt: '2024-03-22T13:20:00Z',
  },  {
    id: '16',
    name: 'Professional Milk Pitcher 600ml',
    description: 'Stainless steel pitcher with ergonomic design for precise pouring. Ideal for creating latte art.',
    sku: 'ACC-PIT-016',
    price: 450,
    images: [
      'https://images.pexels.com/photos/7474390/pexels-photo-7474390.jpeg',
      'https://images.pexels.com/photos/9012110/pexels-photo-9012110.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 40,
    minOrderQuantity: 3,    specifications: {
      'Material': '304 Stainless steel',
      'Capacity': '600ml',
      'Handle': 'Ergonomic insulated',
      'Spout': 'Fine pouring',
      'Dimensions': '15 x 9 x 12 cm',
    },
    isActive: true,
    createdAt: '2024-02-20T09:10:00Z',
    updatedAt: '2024-03-25T11:30:00Z',
  },  {
    id: '17',
    name: 'Commercial Drip Coffee Machine',
    description: 'High-performance drip coffee machine with capacity for 100 cups per hour. Ideal for high-volume coffee shops.',
    sku: 'MAC-FIL-017',
    price: 12500,
    salePrice: 11000,
    images: [
      'https://images.pexels.com/photos/2467287/pexels-photo-2467287.jpeg',
      'https://images.pexels.com/photos/3095224/pexels-photo-3095224.jpeg',
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 5,
    minOrderQuantity: 1,    specifications: {
      'Capacity': '100 cups/hour',
      'Power': '2200W',
      'Water Tank': '4L',
      'Dimensions': '35 x 40 x 55 cm',
      'Weight': '18kg',
      'Voltage': '220V',
    },
    isActive: true,
    createdAt: '2024-02-25T13:50:00Z',
    updatedAt: '2024-03-27T15:15:00Z',
  },  {
    id: '18',
    name: 'Kenya AA Coffee 1kg',
    description: 'Single-origin coffee from the Nyeri region with bright red fruit notes and a velvety body.',
    sku: 'COF-KEN-018',
    price: 490,
    images: [
      'https://images.pexels.com/photos/942680/pexels-photo-942680.jpeg',
      'https://images.pexels.com/photos/2396220/pexels-photo-2396220.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 35,
    minOrderQuantity: 2,    specifications: {
      'Origin': 'Kenya',
      'Roast': 'Medium',
      'Notes': 'Red fruits, Currants, Dark chocolate',
      'Recommended Method': 'Pour Over, Aeropress',
      'Intensity': '7/10',
      'Weight': '1kg',
    },
    isActive: true,
    createdAt: '2024-03-01T08:40:00Z',
    updatedAt: '2024-03-29T10:10:00Z',
  },  {
    id: '19',
    name: 'Reusable Filter Set',
    description: 'Set of 4 reusable stainless steel filters compatible with multiple brewing methods.',
    sku: 'ACC-FIL-019',
    price: 580,
    salePrice: 520,
    images: [
      'https://images.pexels.com/photos/9084535/pexels-photo-9084535.jpeg',
      'https://images.pexels.com/photos/7474347/pexels-photo-7474347.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 55,
    minOrderQuantity: 2,    specifications: {
      'Material': 'Stainless steel',
      'Quantity': '4 filters',
      'Compatibility': 'V60, Chemex, Aeropress, Kalita',
      'Washing': 'Dishwasher safe',
      'Dimensions': 'Various sizes',
    },
    isActive: true,
    createdAt: '2024-03-05T15:25:00Z',
    updatedAt: '2024-03-30T12:35:00Z',
  },  {
    id: '20',
    name: 'Guatemala Antigua Coffee 500g',
    description: 'Coffee from the highlands of Guatemala with a balanced profile and notes of chocolate and spices.',
    sku: 'COF-GUA-020',
    price: 310,
    salePrice: 280,
    images: [
      'https://images.pexels.com/photos/2878730/pexels-photo-2878730.jpeg',
      'https://images.pexels.com/photos/1879321/pexels-photo-1879321.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 70,
    minOrderQuantity: 3,    specifications: {
      'Origin': 'Guatemala',
      'Roast': 'Medium',
      'Notes': 'Chocolate, Cinnamon, Orange',
      'Recommended Method': 'Espresso, Moka',
      'Intensity': '6/10',
      'Weight': '500g',
    },
    isActive: true,
    createdAt: '2024-03-10T11:15:00Z',
    updatedAt: '2024-04-01T14:20:00Z',
  },  {
    id: '21',
    name: 'Glass French Press 1L',
    description: 'Heat-resistant borosilicate glass French press with stainless steel filter.',
    sku: 'ACC-FRP-021',
    price: 690,
    images: [
      'https://images.pexels.com/photos/6541390/pexels-photo-6541390.jpeg',
      'https://images.pexels.com/photos/6542384/pexels-photo-6542384.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 25,
    minOrderQuantity: 2,    specifications: {
      'Material': 'Borosilicate glass and stainless steel',
      'Capacity': '1L (8 cups)',
      'Filter': 'Double mesh stainless steel',
      'Resistance': 'Dishwasher safe',
      'Dimensions': '15 x 15 x 22 cm',
    },
    isActive: true,
    createdAt: '2024-03-15T09:30:00Z',
    updatedAt: '2024-04-03T13:40:00Z',
  },  {
    id: '22',
    name: 'Basic Barista Kit',
    description: 'Complete kit for beginner baristas: tamper, milk pitcher, thermometer and cleaning brushes.',
    sku: 'ACC-KIT-022',
    price: 1850,
    salePrice: 1650,
    images: [
      'https://images.pexels.com/photos/3020919/pexels-photo-3020919.jpeg',
      'https://images.pexels.com/photos/4226896/pexels-photo-4226896.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 18,
    minOrderQuantity: 1,    specifications: {
      'Contents': 'Tamper 58mm, Pitcher 350ml, Digital thermometer, Brush set',
      'Material': 'Stainless steel',
      'Box': 'Storage case',
      'Guide': 'Basic barista manual',
    },
    isActive: true,
    createdAt: '2024-03-20T13:45:00Z',
    updatedAt: '2024-04-05T10:15:00Z',
  },  {
    id: '23',
    name: 'Professional Capsule Machine',
    description: 'High-speed capsule machine with rapid heating system. Ideal for offices.',
    sku: 'MAC-CAP-023',
    price: 8500,
    images: [
      'https://images.pexels.com/photos/4350059/pexels-photo-4350059.jpeg',
      'https://images.pexels.com/photos/4350075/pexels-photo-4350075.jpeg',
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 12,
    minOrderQuantity: 1,    specifications: {
      'Power': '1500W',
      'Tank Capacity': '2.5L',
      'Pressure': '19 bar',
      'Heating Time': '25 seconds',
      'Dimensions': '28 x 38 x 22 cm',
      'Weight': '7kg',
    },
    isActive: true,
    createdAt: '2024-03-25T16:20:00Z',
    updatedAt: '2024-04-08T11:50:00Z',
  },  {
    id: '24',
    name: 'Costa Rica Tarrazu Coffee 1kg',
    description: 'High-altitude coffee with tropical fruit notes and a medium-full body. Sustainable cultivation.',
    sku: 'COF-COS-024',
    price: 460,
    salePrice: 410,
    images: [
      'https://images.pexels.com/photos/1627933/pexels-photo-1627933.jpeg',
      'https://images.pexels.com/photos/2260867/pexels-photo-2260867.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 40,
    minOrderQuantity: 2,    specifications: {
      'Origin': 'Costa Rica',
      'Roast': 'Medium',
      'Notes': 'Mango, Pineapple, Honey',
      'Recommended Method': 'Pour Over, French Press',
      'Intensity': '6/10',
      'Weight': '1kg',
    },
    isActive: true,
    createdAt: '2024-03-28T08:50:00Z',
    updatedAt: '2024-04-10T15:30:00Z',
  },
];

// Exportar la función que crea los productos adicionales
export default createAdditionalProducts;
