import { Product } from './lib/types';
import { categories, suppliers } from './catalogData';
import createAdditionalProducts from './additionalMockProducts';

// Re-export categories and suppliers to maintain compatibility with existing code
export { categories, suppliers };

// Mock Products
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Italian Espresso Coffee 1kg',
    description: 'Medium roast coffee with chocolate and caramel notes. Perfect for professional espresso machines.',
    sku: 'COF-ESP-001',
    price: 450,
    salePrice: 399,
    images: [
      'https://images.pexels.com/photos/3020919/pexels-photo-3020919.jpeg',
      'https://images.pexels.com/photos/2252559/pexels-photo-2252559.jpeg',
      'https://images.pexels.com/photos/4820804/pexels-photo-4820804.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 150,
    minOrderQuantity: 5,
    specifications: {
      'Origin': 'Italy',
      'Roast': 'Medium',
      'Notes': 'Chocolate, Caramel, Nuts',
      'Recommended Method': 'Espresso',
      'Intensity': '8/10',
      'Weight': '1kg',
    },
    isActive: true,
    createdAt: '2023-05-15T10:30:00Z',
    updatedAt: '2023-08-22T14:45:00Z',
  },
  {
    id: '2',
    name: 'Professional Espresso Machine Pro 3000',
    description: 'Professional espresso machine with 2 groups, 10L boiler and advanced thermal stability system.',
    sku: 'MAQ-ESP-3000',
    price: 45000,
    images: [
      'https://images.pexels.com/photos/2878709/pexels-photo-2878709.jpeg',
      'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg',
      'https://images.pexels.com/photos/6802983/pexels-photo-6802983.jpeg',
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 10,
    minOrderQuantity: 1,
    specifications: {
      'Groups': '2',
      'Power': '3200W',
      'Boiler Capacity': '10L',
      'Pressure': '9 bar',
      'Dimensions': '72 x 55 x 53 cm',
      'Weight': '64kg',
      'Voltage': '220V',
    },
    isActive: true,
    createdAt: '2023-06-10T08:15:00Z',
    updatedAt: '2023-09-01T11:20:00Z',
  },
  {
    id: '3',
    name: 'Professional Stainless Steel Tamper',
    description: 'Professional barista tamper with ergonomic handle and 58mm stainless steel base.',
    sku: 'ACC-TAM-001',
    price: 890,
    salePrice: 750,
    images: [
      'https://images.pexels.com/photos/4792701/pexels-photo-4792701.jpeg',
      'https://images.pexels.com/photos/4792719/pexels-photo-4792719.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 45,
    minOrderQuantity: 2,
    specifications: {
      'Material': 'Stainless Steel',
      'Diameter': '58mm',
      'Weight': '500g',
      'Color': 'Silver/Black',
    },
    isActive: true,
    createdAt: '2023-04-20T09:45:00Z',
    updatedAt: '2023-07-15T13:10:00Z',
  },
  {
    id: '4',
    name: 'Organic Specialty Coffee 500g',
    description: 'Fair trade certified organic coffee. Floral and fruity notes with a clean finish.',
    sku: 'COF-ESP-002',
    price: 320,
    images: [
      'https://images.pexels.com/photos/1695052/pexels-photo-1695052.jpeg',
      'https://images.pexels.com/photos/2252558/pexels-photo-2252558.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 80,
    minOrderQuantity: 3,
    specifications: {
      'Origin': 'Chiapas, Mexico',
      'Roast': 'Medium-Light',
      'Notes': 'Floral, Citrus, Honey',
      'Recommended Method': 'Pour over, French press',
      'Certification': 'Organic, Fair Trade',
      'Weight': '500g',
    },
    isActive: true,
    createdAt: '2023-07-05T11:30:00Z',
    updatedAt: '2023-09-10T09:15:00Z',
  },
  {
    id: '5',
    name: 'Premium Coffee Grinder',
    description: 'Professional coffee grinder with 45 grind settings and digital timer.',
    sku: 'ACC-GRD-001',
    price: 3600,
    salePrice: 2999,
    images: [
      'https://images.pexels.com/photos/3570708/pexels-photo-3570708.jpeg',
      'https://images.pexels.com/photos/5864290/pexels-photo-5864290.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 15,
    minOrderQuantity: 1,
    specifications: {
      'Material': 'Acero inoxidable y plástico ABS',
      'Potencia': '150W',
      'Capacidad': '250g',
      'Ajustes de molienda': '45',
      'Dimensiones': '22 x 13 x 35 cm',
      'Peso': '2.8kg',
    },
    isActive: true,
    createdAt: '2023-08-12T14:20:00Z',
    updatedAt: '2023-09-25T10:30:00Z',
  },
  {
    id: '6',
    name: 'Paquete de Vasos Biodegradables 12oz (100u)',
    description: 'Vasos para café biodegradables y compostables con diseño térmico para bebidas calientes.',
    sku: 'ACC-VAS-001',
    price: 580,
    images: [
      'https://images.pexels.com/photos/3407774/pexels-photo-3407774.jpeg',
      'https://images.pexels.com/photos/7474224/pexels-photo-7474224.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[0],
    stock: 200,
    minOrderQuantity: 5,
    specifications: {
      'Material': 'PLA Compostable',
      'Capacidad': '12oz (355ml)',
      'Unidades': '100',
      'Certificación': 'Compostable, Sin BPA',
      'Dimensiones': '9cm (altura) x 8cm (diámetro superior)',
    },
    isActive: true,
    createdAt: '2023-05-30T15:45:00Z',
    updatedAt: '2023-08-05T12:10:00Z',
  },
  {
    id: '7',
    name: 'Espresso Blend Signature 1kg',
    description: 'Nuestra mezcla insignia para espresso con un perfil equilibrado de chocolate, frutos rojos y caramelo.',
    sku: 'CAF-ESP-003',
    price: 480,
    images: [
      'https://images.pexels.com/photos/977876/pexels-photo-977876.jpeg',
      'https://images.pexels.com/photos/894695/pexels-photo-894695.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 120,
    minOrderQuantity: 5,
    specifications: {
      'Origen': 'Blend (Brasil, Colombia, Etiopía)',
      'Tueste': 'Medio-Oscuro',
      'Notas': 'Chocolate, Frutos rojos, Caramelo',
      'Método recomendado': 'Espresso, Moka',
      'Intensidad': '9/10',
      'Peso': '1kg',
    },
    isActive: true,
    createdAt: '2023-07-18T09:20:00Z',
    updatedAt: '2023-09-15T14:35:00Z',
  },
  {
    id: '8',
    name: 'Filtros de papel para V60 (100u)',
    description: 'Filtros de papel premium para métodos de preparación V60. Sin blanquear para un sabor más puro.',
    sku: 'ACC-FIL-001',
    price: 180,
    images: [
      'https://images.pexels.com/photos/4226896/pexels-photo-4226896.jpeg',
      'https://images.pexels.com/photos/6311447/pexels-photo-6311447.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[0],
    stock: 250,
    minOrderQuantity: 10,
    specifications: {
      'Material': 'Papel sin blanquear',
      'Tipo': 'V60 01-02',
      'Unidades': '100',
      'Características': 'Biodegradable, Compostable',
    },
    isActive: true,
    createdAt: '2023-06-25T12:40:00Z',
    updatedAt: '2023-08-30T11:15:00Z',
  },
  // Añadir los productos adicionales
  ...createAdditionalProducts(categories, suppliers)
];