import { Product, Category, Supplier } from './lib/types';

// Mock Categories
export const categories: Category[] = [
  {
    id: '1',
    name: 'Café en grano',
    slug: 'cafe-grano',
    description: 'Granos de café de la más alta calidad',
    image: 'https://images.pexels.com/photos/685527/pexels-photo-685527.jpeg',
  },
  {
    id: '2',
    name: 'Máquinas profesionales',
    slug: 'maquinas',
    description: 'Equipos profesionales para preparación de café',
    image: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
  },
  {
    id: '3',
    name: 'Accesorios',
    slug: 'accesorios',
    description: 'Accesorios para mejorar tu experiencia cafetera',
    image: 'https://images.pexels.com/photos/2879812/pexels-photo-2879812.jpeg',
  },
];

// Mock Suppliers
export const suppliers: Supplier[] = [
  {
    id: '1',
    name: 'Café Italiano S.A.',
    description: 'Importador directo de café italiano de alta calidad',
    contactEmail: 'contacto@cafeitaliano.com',
    contactPhone: '+52 55 1234 5678',
    minOrderValue: 5000,
    deliveryTime: '3-5 días',
  },
  {
    id: '2',
    name: 'ImportCoffee',
    logo: 'https://images.pexels.com/photos/1337386/pexels-photo-1337386.jpeg',
    description: 'Especialistas en máquinas para café',
    contactEmail: 'ventas@importcoffee.com',
    contactPhone: '+52 55 8765 4321',
    minOrderValue: 10000,
    deliveryTime: '5-7 días',
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Café Espresso Italiano Premium 1kg',
    description: 'Café de tueste medio con notas de chocolate y caramelo. Perfecto para máquinas de espresso profesionales.',
    sku: 'CAF-ESP-001',
    price: 450,
    salePrice: 399,
    images: [
      'https://images.pexels.com/photos/3020919/pexels-photo-3020919.jpeg',
      'https://images.pexels.com/photos/2252559/pexels-photo-2252559.jpeg',
      'https://images.pexels.com/photos/4820804/pexels-photo-4820804.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 150,
    minOrderQuantity: 5,
    specifications: {
      'Origen': 'Italia',
      'Tueste': 'Medio',
      'Notas': 'Chocolate, Caramelo, Frutos secos',
      'Método recomendado': 'Espresso',
      'Intensidad': '8/10',
      'Peso': '1kg',
    },
    isActive: true,
    createdAt: '2023-05-15T10:30:00Z',
    updatedAt: '2023-08-22T14:45:00Z',
  },
  {
    id: '2',
    name: 'Máquina de Espresso Profesional Pro 3000',
    description: 'Máquina de espresso profesional con 2 grupos, caldera de 10L y sistema de estabilidad térmica avanzado.',
    sku: 'MAQ-ESP-3000',
    price: 45000,
    images: [
      'https://images.pexels.com/photos/2878709/pexels-photo-2878709.jpeg',
      'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg',
      'https://images.pexels.com/photos/6802983/pexels-photo-6802983.jpeg',
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 10,
    minOrderQuantity: 1,
    specifications: {
      'Grupos': '2',
      'Potencia': '3200W',
      'Capacidad caldera': '10L',
      'Presión': '9 bar',
      'Dimensiones': '72 x 55 x 53 cm',
      'Peso': '64kg',
      'Voltaje': '220V',
    },
    isActive: true,
    createdAt: '2023-06-10T08:15:00Z',
    updatedAt: '2023-09-01T11:20:00Z',
  },
  {
    id: '3',
    name: 'Tamper Profesional de Acero Inoxidable',
    description: 'Tamper de barista profesional con mango ergonómico y base de acero inoxidable de 58mm.',
    sku: 'ACC-TAM-001',
    price: 890,
    salePrice: 750,
    images: [
      'https://images.pexels.com/photos/4792701/pexels-photo-4792701.jpeg',
      'https://images.pexels.com/photos/4792719/pexels-photo-4792719.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 45,
    minOrderQuantity: 2,
    specifications: {
      'Material': 'Acero inoxidable',
      'Diámetro': '58mm',
      'Peso': '500g',
      'Color': 'Plata/Negro',
    },
    isActive: true,
    createdAt: '2023-04-20T09:45:00Z',
    updatedAt: '2023-07-15T13:10:00Z',
  },
  {
    id: '4',
    name: 'Café de Especialidad Orgánico 500g',
    description: 'Café orgánico de comercio justo con certificación. Notas florales y afrutadas con un acabado limpio.',
    sku: 'CAF-ESP-002',
    price: 320,
    images: [
      'https://images.pexels.com/photos/1695052/pexels-photo-1695052.jpeg',
      'https://images.pexels.com/photos/2252558/pexels-photo-2252558.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 80,
    minOrderQuantity: 3,
    specifications: {
      'Origen': 'Chiapas, México',
      'Tueste': 'Medio-Claro',
      'Notas': 'Flores, Cítricos, Miel',
      'Método recomendado': 'Pour over, Prensa francesa',
      'Certificación': 'Orgánico, Comercio Justo',
      'Peso': '500g',
    },
    isActive: true,
    createdAt: '2023-07-05T11:30:00Z',
    updatedAt: '2023-09-10T09:15:00Z',
  },
  {
    id: '5',
    name: 'Molinillo de Café Premium',
    description: 'Molinillo de café profesional con 45 configuraciones de molienda y temporizador digital.',
    sku: 'ACC-MOL-001',
    price: 3600,
    salePrice: 2999,
    images: [
      'https://images.pexels.com/photos/3570708/pexels-photo-3570708.jpeg',
      'https://images.pexels.com/photos/5864290/pexels-photo-5864290.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 15,
    minOrderQuantity: 1,
    specifications: {
      'Material': 'Acero inoxidable y plástico ABS',
      'Potencia': '150W',
      'Capacidad': '250g',
      'Ajustes de molienda': '45',
      'Dimensiones': '22 x 13 x 35 cm',
      'Peso': '2.8kg',
    },
    isActive: true,
    createdAt: '2023-08-12T14:20:00Z',
    updatedAt: '2023-09-25T10:30:00Z',
  },
  {
    id: '6',
    name: 'Paquete de Vasos Biodegradables 12oz (100u)',
    description: 'Vasos para café biodegradables y compostables con diseño térmico para bebidas calientes.',
    sku: 'ACC-VAS-001',
    price: 580,
    images: [
      'https://images.pexels.com/photos/3407774/pexels-photo-3407774.jpeg',
      'https://images.pexels.com/photos/7474224/pexels-photo-7474224.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[0],
    stock: 200,
    minOrderQuantity: 5,
    specifications: {
      'Material': 'PLA Compostable',
      'Capacidad': '12oz (355ml)',
      'Unidades': '100',
      'Certificación': 'Compostable, Sin BPA',
      'Dimensiones': '9cm (altura) x 8cm (diámetro superior)',
    },
    isActive: true,
    createdAt: '2023-05-30T15:45:00Z',
    updatedAt: '2023-08-05T12:10:00Z',
  },
  {
    id: '7',
    name: 'Espresso Blend Signature 1kg',
    description: 'Nuestra mezcla insignia para espresso con un perfil equilibrado de chocolate, frutos rojos y caramelo.',
    sku: 'CAF-ESP-003',
    price: 480,
    images: [
      'https://images.pexels.com/photos/977876/pexels-photo-977876.jpeg',
      'https://images.pexels.com/photos/894695/pexels-photo-894695.jpeg',
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 120,
    minOrderQuantity: 5,
    specifications: {
      'Origen': 'Blend (Brasil, Colombia, Etiopía)',
      'Tueste': 'Medio-Oscuro',
      'Notas': 'Chocolate, Frutos rojos, Caramelo',
      'Método recomendado': 'Espresso, Moka',
      'Intensidad': '9/10',
      'Peso': '1kg',
    },
    isActive: true,
    createdAt: '2023-07-18T09:20:00Z',
    updatedAt: '2023-09-15T14:35:00Z',
  },
  {
    id: '8',
    name: 'Filtros de papel para V60 (100u)',
    description: 'Filtros de papel premium para métodos de preparación V60. Sin blanquear para un sabor más puro.',
    sku: 'ACC-FIL-001',
    price: 180,
    images: [
      'https://images.pexels.com/photos/4226896/pexels-photo-4226896.jpeg',
      'https://images.pexels.com/photos/6311447/pexels-photo-6311447.jpeg',
    ],
    category: categories[2],
    supplier: suppliers[0],
    stock: 250,
    minOrderQuantity: 10,
    specifications: {
      'Material': 'Papel sin blanquear',
      'Tipo': 'V60 01-02',
      'Unidades': '100',
      'Características': 'Biodegradable, Compostable',
    },
    isActive: true,
    createdAt: '2023-06-25T12:40:00Z',
    updatedAt: '2023-08-30T11:15:00Z',
  },
];