import { Product } from "./lib/types";
import { categories, suppliers } from "./catalogData";
import createAdditionalProducts from "./additionalMockProducts";

// Re-export categories and suppliers to maintain compatibility with existing code
export { categories, suppliers };

// Mock Products
export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Res tierra CASE 6 BAGS RES TIERRA SELECT 1kg BEANS",
    description:
      "Café de tueste medio con notas de chocolate y caramelo. Perfecto para máquinas de espresso profesionales.",
    sku: "COF-ESP-001",
    price: 450,
    salePrice: 399,
    images: [
      "https://prodotti.com.co/wp-content/uploads/2022/03/CAFE-LAVAZZA-Prontissimo-Classico-prodotti.png",
      "https://e-horeca.mk/wp-content/uploads/2021/02/lavazza-espresso-italiano-cremoso-1kg.jpg",
      "https://images.pexels.com/photos/585750/pexels-photo-585750.jpeg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 150,
    minOrderQuantity: 5,
    specifications: {
      Origin: "Italy",
      Roast: "Medium",
      Notes: "Chocolate, Caramelo, Nueces",
      "Recommended Method": "Espresso",
      Intensity: "8/10",
      Weight: "1kg",
    },
    isActive: true,
    createdAt: "2023-05-15T10:30:00Z",
    updatedAt: "2023-08-22T14:45:00Z",
  },
  {
    id: "2",
    name: "LB 300 USA CLASSY MINI 120V",
    description:
      "Máquina de espresso profesional con 2 grupos, caldera de 10L y sistema avanzado de estabilidad térmica.",
    sku: "MAQ-ESP-3000",
    price: 45000,
    images: [
      "https://e-horeca.mk/wp-content/uploads/2021/02/lavazza-espresso-italiano-cremoso-1kg.jpg",
      "https://www.maxima.com/images/products/large/espresso-machine-2-group-professional.jpg",
      "https://images.pexels.com/photos/6802983/pexels-photo-6802983.jpeg",
    ],
    category: categories[1],
    supplier: suppliers[1],
    stock: 10,
    minOrderQuantity: 1,
    specifications: {
      Groups: "2",
      Power: "3200W",
      "Boiler Capacity": "10L",
      Pressure: "9 bar",
      Dimensions: "72 x 55 x 53 cm",
      Weight: "64kg",
      Voltage: "220V",
    },
    isActive: true,
    createdAt: "2023-06-10T08:15:00Z",
    updatedAt: "2023-09-01T11:20:00Z",
  },
  {
    id: "3",
    name: "BIOCAF GRINDER CLEANING TABLETS 234 G",
    description:
      "Tamper profesional de barista con mango ergonómico y base de acero inoxidable de 58mm.",
    sku: "ACC-TAM-001",
    price: 890,
    salePrice: 750,
    images: [
      "https://mcgrocer.com/cdn/shop/files/lavazza-espresso-italiano-classico-coffee-beans-250g-41784847073518_grande.jpg?v=1742856366",
      "https://www.corporatecoffee.com.au/wp-content/uploads/2023/05/stainless-steel-tamper-58mm.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 45,
    minOrderQuantity: 2,
    specifications: {
      Material: "Stainless Steel",
      Diameter: "58mm",
      Weight: "500g",
      Color: "Silver/Black",
    },
    isActive: true,
    createdAt: "2023-04-20T09:45:00Z",
    updatedAt: "2023-07-15T13:10:00Z",
  },
  {
    id: "4",
    name: "Res tierras Bras CS.6 S.P.RESTIERRA BRAS100%AR FLT 226,8",
    description:
      "Café orgánico certificado de comercio justo. Notas florales y afrutadas con un final limpio.",
    sku: "COF-ESP-002",
    price: 320,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqCQyTFA7o-daq9xe1yUcsiRkfvu1wGwB6hw&s",
      "https://www.organicfacts.net/wp-content/uploads/organic-coffee-beans.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 80,
    minOrderQuantity: 3,
    specifications: {
      Origin: "Chiapas, Mexico",
      Roast: "Medium-Light",
      Notes: "Floral, Citrus, Honey",
      "Recommended Method": "Pour over, French press",
      Certification: "Organic, Fair Trade",
      Weight: "500g",
    },
    isActive: true,
    createdAt: "2023-07-05T11:30:00Z",
    updatedAt: "2023-09-10T09:15:00Z",
  },
  {
    id: "5",
    name: "BIOCAF ESPRESSO CLEANING POWDER 500ML",
    description:
      "Molinillo de café profesional con 45 configuraciones de molienda y temporizador digital.",
    sku: "ACC-GRD-001",
    price: 3600,
    salePrice: 2999,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQreRf2ScuDBaWUfPcvfymcIGhnYfO7FmPjJw&s",
      "https://www.williams-sonoma.com/wsimgs/rk/images/dp/wcm/202341/0018/braun-burr-coffee-grinder-main.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 15,
    minOrderQuantity: 1,
    specifications: {
      Material: "Acero inoxidable y plástico ABS",
      Potencia: "150W",
      Capacidad: "250g",
      "Ajustes de molienda": "45",
      Dimensiones: "22 x 13 x 35 cm",
      Peso: "2.8kg",
    },
    isActive: true,
    createdAt: "2023-08-12T14:20:00Z",
    updatedAt: "2023-09-25T10:30:00Z",
  },
  {
    id: "6",
    name: "FILTER GOURMET 20138",
    description:
      "Vasos para café biodegradables y compostables con diseño térmico para bebidas calientes.",
    sku: "ACC-VAS-001",
    price: 580,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7rOKt68BCnZZcgaC51WBnsqMHis06-cxfGA&s",
      "https://www.ecocups.com/images/biodegradable-coffee-cups-12oz.jpg",
    ],
    category: categories[2],
    supplier: suppliers[0],
    stock: 200,
    minOrderQuantity: 5,
    specifications: {
      Material: "PLA Compostable",
      Capacidad: "12oz (355ml)",
      Unidades: "100",
      Certificación: "Compostable, Sin BPA",
      Dimensiones: "9cm (altura) x 8cm (diámetro superior)",
    },
    isActive: true,
    createdAt: "2023-05-30T15:45:00Z",
    updatedAt: "2023-08-05T12:10:00Z",
  },
  {
    id: "7",
    name: "Res tierra CASE 6 PC.RES TIERRA BRAS BLEND 1000 B",
    description:
      "Nuestra mezcla insignia para espresso con perfil equilibrado de chocolate, frutos rojos y caramelo.",
    sku: "CAF-ESP-003",
    price: 480,
    images: [
      "https://lagranbodega.vteximg.com.br/arquivos/ids/289150-600-600/7502247423176.jpg?v=638024202260300000",
      "https://e-horeca.mk/wp-content/uploads/2021/03/kimbo-espresso-bar-premium-1kg.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 120,
    minOrderQuantity: 5,
    specifications: {
      Origen: "Blend (Brasil, Colombia, Etiopía)",
      Tueste: "Medio-Oscuro",
      Notas: "Chocolate, Frutos rojos, Caramelo",
      "Método recomendado": "Espresso, Moka",
      Intensidad: "9/10",
      Peso: "1kg",
    },
    isActive: true,
    createdAt: "2023-07-18T09:20:00Z",
    updatedAt: "2023-09-15T14:35:00Z",
  },
  {
    id: "8",
    name: "DEK CASE 12 PACKS DECAFF FILTER 500BEANS",
    description:
      "Filtros de papel premium para métodos de preparación V60. Sin blanquear para un sabor más puro.",
    sku: "ACC-FIL-001",
    price: 180,
    images: [
      "https://e-horeca.mk/wp-content/uploads/2021/03/kimbo-espresso-bar-premium-1kg.jpg",
      "https://v60filters.com/images/v60-paper-filters-100-pack.jpg",
    ],
    category: categories[2],
    supplier: suppliers[0],
    stock: 250,
    minOrderQuantity: 10,
    specifications: {
      Material: "Papel sin blanquear",
      Tipo: "V60 01-02",
      Unidades: "100",
      Características: "Biodegradable, Compostable",
    },
    isActive: true,
    createdAt: "2023-06-25T12:40:00Z",
    updatedAt: "2023-08-30T11:15:00Z",
  },
  {
    id: "9",
    name: "Cold brew concentrate 7:1",
    description:
      "Café extraído en frío durante 18 horas. Sabor suave, dulce y menos ácido. Ideal para servir con hielo.",
    sku: "COF-CBR-001",
    price: 280,
    images: [
      "https://e-horeca.mk/wp-content/uploads/2021/03/jacobs-barista-editions-espresso.jpg",
      "https://www.coldbrewcoffee.com/images/cold-brew-bottle-1l.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 60,
    minOrderQuantity: 2,
    specifications: {
      Origen: "Colombia",
      Extracción: "Cold Brew",
      Notas: "Cacao, Almendra, Miel",
      Conservación: "Refrigerado",
      Peso: "1L",
    },
    isActive: true,
    createdAt: "2023-06-22T11:10:00Z",
    updatedAt: "2023-09-03T16:00:00Z",
  },
  {
    id: "10",
    name: "SOFT PACKS GRAN AROMA COSTIERA 340 Case 6",
    description:
      "Diseño elegante con vidrio templado y filtro de acero inoxidable. Ideal para preparar café de manera manual.",
    sku: "ACC-PRE-001",
    price: 690,
    salePrice: 590,
    images: [
      "https://e-horeca.mk/wp-content/uploads/2019/11/super-crema.jpg",
      "https://shop.original-unverpackt.de/cdn/shop/products/french-press-glass-350ml.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 35,
    minOrderQuantity: 1,
    specifications: {
      Capacidad: "350ml",
      Material: "Vidrio y acero inoxidable",
      Color: "Transparente/Negro",
      Método: "French Press",
    },
    isActive: true,
    createdAt: "2023-07-11T10:25:00Z",
    updatedAt: "2023-09-12T08:45:00Z",
  },
  {
    id: "11",
    name: "SOFT PACKS CLASSICO DOLCEVITA 340",
    description:
      "Cápsulas compatibles con Nespresso. Mezcla intensa de tueste oscuro con notas de cacao y nuez.",
    sku: "CAF-CAP-001",
    price: 150,
    images: [
      "https://e-horeca.mk/wp-content/uploads/2018/12/lavazza-aroma-crema.png",
      "https://www.nespresso.com/shared_res/agility/n-components/product-media/capsules-intenso-10pack.jpg",
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 180,
    minOrderQuantity: 5,
    specifications: {
      Compatibilidad: "Nespresso",
      Intensidad: "10/10",
      Tueste: "Oscuro",
      Unidades: "10 cápsulas",
    },
    isActive: true,
    createdAt: "2023-08-05T13:30:00Z",
    updatedAt: "2023-09-20T12:15:00Z",
  },
  {
    id: "12",
    name: "SOFT PACKS PERF HOUSE BL 340",
    description:
      "Incluye tamper, nivelador y alfombrilla de prensado. Ideal para quienes inician en el arte del espresso.",
    sku: "KIT-BAR-001",
    price: 1350,
    images: [
      "https://cafedujour.es/media/catalog/product/cache/bc57bd4ccef7bb06740e293c0bbfd2e9/k/i/kimboaromagold.png",
      "https://www.corporatecoffee.com.au/wp-content/uploads/2023/05/basic-barista-kit-complete.jpg",
    ],
    category: categories[2],
    supplier: suppliers[1],
    stock: 22,
    minOrderQuantity: 1,
    specifications: {
      Contenido: "Tamper, Nivelador, Alfombrilla",
      Material: "Acero inoxidable, silicona",
      Compatible: "58mm portafiltros",
    },
    isActive: true,
    createdAt: "2023-07-30T14:50:00Z",
    updatedAt: "2023-09-10T16:40:00Z",
  },  {
    id: "13",
    name: "Case 100 C.BLUE RES TIERRA SELECTION",
    description:
      "Café arábica lavado con notas florales y afrutadas. Ideal para métodos como Chemex o V60.",
    sku: "CAF-SIN-001",
    price: 210,
    images: [
      "https://universaldolce.com/wp-content/uploads/catalogo/WEB_LAV2214.jpg"
    ],
    category: categories[0],
    supplier: suppliers[0],
    stock: 100,
    minOrderQuantity: 2,
    specifications: {
      Origen: "Yirgacheffe, Etiopía",
      Tueste: "Claro",
      Notas: "Jazmín, Cítricos, Té negro",
      "Método recomendado": "V60, Chemex",
      Peso: "250g",
    },
    isActive: true,
    createdAt: "2023-08-15T10:05:00Z",
    updatedAt: "2023-09-22T13:25:00Z",
  },
  // Añadir productos generados dinámicamente
  ...createAdditionalProducts(categories, suppliers),
];